### ISSUE TITLE
Examples in documentation not working

### ISSUE THREAD

**Issue by tiagovla** [rcarriga/neotest#1]
Are the examples supposed to work like this?
https://github.com/rcarriga/neotest/blob/6dede28d9a08157ed955b04278cddc4faa9d8708/doc/neotest.txt#L253

They do work like this:
```lua
lua require("neotest").run.run(vim.fn.expand("%")) 
```

Error:
```
Error executing lua [string ":lua"]:1: attempt to call field 'run' (a table value)
```

**Comment by rcarriga** [comment]
Ah they were outdated, fixed now. Thanks for the report!

**Comment by tiagovla** [comment]
This one too:
https://github.com/rcarriga/neotest/blob/70eba5a7c08d5ec31d2f747959c7658a1df26911/doc/neotest.txt#L225

**Comment by wookayin** [comment]
>  lua require("neotest").open({ enter = true }) 

This one still hasn't been fixed yet, so maybe you could leave this open?

**Comment by rcarriga** [comment]
Fixed that one too thanks! :smile:

**Comment by jim-at-jibba** [comment]
I still get the error above even when running the updated commands. Any ideas?

**Comment by hexdigest** [comment]
Can't get this working. Updated neovim from unstable ppa to 0.8.0-dev and non of examplese working.
They also didn't work on stable 0.6.4 version but giving different output.

```
:lua require("neotest").run.run(vim.fn.expand("%"))

E5108: Error executing lua [string ":lua"]:1: attempt to index field 'run' (a nil value)
stack traceback:                                                                                                                                                   
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```
